"""Add durable background delivery batches and a chat-wide event cursor.

Revision ID: 051
Revises: 050
Create Date: 2026-07-25
"""

from alembic import op


revision = "051"
down_revision = "050"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Test/bootstrap environments may materialize the latest ORM metadata
    # before replaying migrations. Keep this historical step idempotent when
    # the legacy delivery column is no longer present in that latest model;
    # revision 053 migrates and removes it again.
    op.execute(
        "ALTER TABLE chat_tool_jobs "
        "ADD COLUMN IF NOT EXISTS consumed_at timestamptz"
    )
    op.execute(
        "ALTER TABLE chat_tool_jobs "
        "ADD COLUMN IF NOT EXISTS delivery_batch_id text"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_chat_tool_jobs_pending_delivery "
        "ON chat_tool_jobs (tenant_id, chat_id, finished_at) "
        "WHERE consumed_at IS NULL AND "
        "status IN ('completed','failed','cancelled')"
    )
    op.execute(
        "ALTER TABLE chat_tool_job_events "
        "ADD COLUMN IF NOT EXISTS event_id bigint "
        "GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS "
        "uq_chat_tool_job_events_event_id "
        "ON chat_tool_job_events (event_id)"
    )
    op.execute(
        "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public "
        "TO vibecanvas_app"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_chat_tool_job_events_event_id")
    op.execute(
        "ALTER TABLE chat_tool_job_events DROP COLUMN IF EXISTS event_id"
    )
    op.execute("DROP INDEX IF EXISTS ix_chat_tool_jobs_pending_delivery")
    op.execute(
        "ALTER TABLE chat_tool_jobs DROP COLUMN IF EXISTS delivery_batch_id"
    )
