"""Add content revisions and durable VFS change events for live Preview.

Revision ID: 052
Revises: 051
Create Date: 2026-07-25
"""

from alembic import op


revision = "052"
down_revision = "051"
branch_labels = None
depends_on = None


def _rls(table: str) -> None:
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    op.execute(
        f"CREATE POLICY tenant_isolation ON {table} FOR ALL "
        "USING (tenant_id = current_setting('app.tenant_id', true)::uuid) "
        "WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid)"
    )
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO vibecanvas_app"
    )


def upgrade() -> None:
    # A content revision is not an access timestamp: reading a VFS row may
    # legitimately touch last_access without changing the bytes.
    for table in ("vfs_artifacts", "vfs_run"):
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS "
            "content_revision text"
        )
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN content_revision "
            "SET DEFAULT gen_random_uuid()::text"
        )
        # These existing tables use FORCE RLS. Alembic deliberately has no
        # tenant GUC because this is a schema-wide backfill, so the owner would
        # otherwise update zero historical rows. NO FORCE lets the table owner
        # bypass RLS for this transaction only; ENABLE remains in place and
        # FORCE is restored before migration commit.
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(
            f"UPDATE {table} SET content_revision = gen_random_uuid()::text "
            "WHERE content_revision IS NULL"
        )
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN content_revision SET NOT NULL"
        )
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS vfs_artifact_events (
            event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id uuid NOT NULL
                REFERENCES tenants(tenant_id) ON DELETE CASCADE
                DEFAULT current_setting('app.tenant_id', true)::uuid,
            scope_kind text NOT NULL,
            scope_id text NOT NULL,
            path text NOT NULL,
            event_type text NOT NULL,
            content_revision text,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_vfs_artifact_events_scope_kind
                CHECK (scope_kind IN ('artifact','run')),
            CONSTRAINT ck_vfs_artifact_events_type
                CHECK (event_type IN ('upsert','delete'))
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_vfs_artifact_events_file_cursor "
        "ON vfs_artifact_events "
        "(tenant_id, scope_kind, scope_id, path, event_id)"
    )
    _rls("vfs_artifact_events")
    op.execute(
        "GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public "
        "TO vibecanvas_app"
    )

    # One trigger function serves both durable artifacts and run-scoped files.
    # It emits only inserts, deletes, path moves and content_revision changes;
    # an LRU last_access touch is intentionally silent.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION emit_vfs_artifact_event()
        RETURNS trigger AS $$
        DECLARE
            kind text := TG_ARGV[0];
            old_scope text;
            new_scope text;
            emitted_id bigint;
        BEGIN
            IF kind = 'run' THEN
                IF TG_OP <> 'INSERT' THEN old_scope := OLD.run_id; END IF;
                IF TG_OP <> 'DELETE' THEN new_scope := NEW.run_id; END IF;
            ELSE
                IF TG_OP <> 'INSERT' THEN old_scope := OLD.scope_id; END IF;
                IF TG_OP <> 'DELETE' THEN new_scope := NEW.scope_id; END IF;
            END IF;

            IF TG_OP = 'DELETE' OR (
                TG_OP = 'UPDATE' AND (
                    old_scope IS DISTINCT FROM new_scope
                    OR OLD.path IS DISTINCT FROM NEW.path
                )
            ) THEN
                INSERT INTO vfs_artifact_events (
                    tenant_id, scope_kind, scope_id, path,
                    event_type, content_revision
                ) VALUES (
                    OLD.tenant_id, kind, old_scope, OLD.path,
                    'delete', NULL
                ) RETURNING event_id INTO emitted_id;
                PERFORM pg_notify('vfs_artifact_events', emitted_id::text);
            END IF;

            IF TG_OP = 'INSERT' OR (
                TG_OP = 'UPDATE' AND (
                    old_scope IS DISTINCT FROM new_scope
                    OR OLD.path IS DISTINCT FROM NEW.path
                    OR OLD.content_revision IS DISTINCT FROM NEW.content_revision
                )
            ) THEN
                INSERT INTO vfs_artifact_events (
                    tenant_id, scope_kind, scope_id, path,
                    event_type, content_revision
                ) VALUES (
                    NEW.tenant_id, kind, new_scope, NEW.path,
                    'upsert', NEW.content_revision
                ) RETURNING event_id INTO emitted_id;
                PERFORM pg_notify('vfs_artifact_events', emitted_id::text);
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_vfs_artifacts_preview_events "
        "ON vfs_artifacts"
    )
    op.execute(
        "CREATE TRIGGER trg_vfs_artifacts_preview_events "
        "AFTER INSERT OR UPDATE OR DELETE ON vfs_artifacts "
        "FOR EACH ROW EXECUTE FUNCTION emit_vfs_artifact_event('artifact')"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_vfs_run_preview_events ON vfs_run"
    )
    op.execute(
        "CREATE TRIGGER trg_vfs_run_preview_events "
        "AFTER INSERT OR UPDATE OR DELETE ON vfs_run "
        "FOR EACH ROW EXECUTE FUNCTION emit_vfs_artifact_event('run')"
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_vfs_run_preview_events ON vfs_run"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_vfs_artifacts_preview_events "
        "ON vfs_artifacts"
    )
    op.execute("DROP FUNCTION IF EXISTS emit_vfs_artifact_event()")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON vfs_artifact_events")
    op.execute("DROP TABLE IF EXISTS vfs_artifact_events")
    for table in ("vfs_run", "vfs_artifacts"):
        op.execute(
            f"ALTER TABLE {table} DROP COLUMN IF EXISTS content_revision"
        )
