"""PDF parser tests. Uses small fixture PDFs in fixtures/pdfs/.

Fixtures are regenerated by ``fixtures/pdfs/_generate_fixtures.py``; if
they ever drift, re-run that script.
"""
from __future__ import annotations

import concurrent.futures
from pathlib import Path

import pytest

from vibecanvas_api.services.parsers.base import (
    EmptyDocumentError,
    EncryptedDocumentError,
)
from vibecanvas_api.services.parsers.pdf import PdfParser

FIXTURES = Path(__file__).parent / "fixtures" / "pdfs"


def _read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def test_pdf_two_pages():
    segments = PdfParser().parse(_read("two_pages.pdf"))
    assert len(segments) == 2
    assert segments[0].metadata == {"page": 1}
    assert segments[1].metadata == {"page": 2}
    assert "page one" in segments[0].text.lower()


def test_pdf_encrypted_raises():
    with pytest.raises(EncryptedDocumentError):
        PdfParser().parse(_read("encrypted.pdf"))


def test_pdf_image_only_raises_empty():
    with pytest.raises(EmptyDocumentError):
        PdfParser().parse(_read("image_only.pdf"))


def test_pdf_concurrent_parses_no_state_leak():
    """Round-2 invariant: PARSER_REGISTRY stores classes, instances are
    per-call, so parallel parse() of different PDFs must not interleave state."""
    blobs = [_read("two_pages.pdf"), _read("one_page.pdf")] * 4

    def parse_one(blob: bytes):
        return PdfParser().parse(blob)

    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as ex:
        results = list(ex.map(parse_one, blobs))
    # Each result has segments matching its source — no cross-contamination.
    for r, b in zip(results, blobs):
        assert sum(len(s.text) for s in r) > 0
    # Two-page sources produce 2 segments, one-page sources produce 1 — order
    # preserved across futures.
    for r, b in zip(results, blobs):
        expected_pages = 2 if b == _read("two_pages.pdf") else 1
        assert len(r) == expected_pages
