# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vibecanvas_api.services.sandbox.proto import sandbox_service_pb2 as vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vibecanvas_api/services/sandbox/proto/sandbox_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub:
    """Stable transport contract. Rich operation payloads remain versioned JSON so
    Runtime/Workflow events can evolve independently without regenerating the
    service for every product event field.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stats = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Stats',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Acquire = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Acquire',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.Connect = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Connect',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectResponse.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Inspect',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/vibecanvas.sandbox.v1.SandboxService/Execute',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.SandboxEvent.FromString,
                _registered_method=True)
        self.Invoke = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Invoke',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Control',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.Release = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Release',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.Checkpoint = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Checkpoint',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.Admin = channel.unary_unary(
                '/vibecanvas.sandbox.v1.SandboxService/Admin',
                request_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminRequest.SerializeToString,
                response_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer:
    """Stable transport contract. Rich operation payloads remain versioned JSON so
    Runtime/Workflow events can evolve independently without regenerating the
    service for every product event field.
    """

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Checkpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Admin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsResponse.SerializeToString,
            ),
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireResponse.SerializeToString,
            ),
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectResponse.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ExecuteRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.SandboxEvent.SerializeToString,
            ),
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlResponse.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ReleaseRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.SerializeToString,
            ),
            'Checkpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.Checkpoint,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointResponse.SerializeToString,
            ),
            'Admin': grpc.unary_unary_rpc_method_handler(
                    servicer.Admin,
                    request_deserializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminRequest.FromString,
                    response_serializer=vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vibecanvas.sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vibecanvas.sandbox.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService:
    """Stable transport contract. Rich operation payloads remain versioned JSON so
    Runtime/Workflow events can evolve independently without regenerating the
    service for every product event field.
    """

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Stats',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Acquire',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Connect',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Inspect',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Execute',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ExecuteRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.SandboxEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Invoke',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Control',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Release',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.ReleaseRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Checkpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Checkpoint',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Admin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibecanvas.sandbox.v1.SandboxService/Admin',
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminRequest.SerializeToString,
            vibecanvas__api_dot_services_dot_sandbox_dot_proto_dot_sandbox__service__pb2.AdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
